version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ticketeria-postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
