version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ticketeria-postgres
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: ticketeria
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
